### ISSUE TITLE
MIDI keyboard support

### ISSUE THREAD

**Issue by ankineri** [ditek/MidiSheetMusic-Android#3]
It would be nice to support MIDI keyboard connections, to learn how to play music.
I've written a very basic implementation: https://github.com/ankineri/MidiSheetMusic-Android
If you like it, I can make a pull request. Or maybe something completely new?

**Comment by ditek** [comment]
Hi. I've actually been wanting to do this for a while but haven't found enough time to work on it. Great that you're interested in that!

I took a look at your code and it looks quite neat! Please feel free to make a pull request.
I just noticed a couple of minor issues after a quick glance. There is a couple of duplicated lines in `.idea/modules.xml` and what seems like a setup-specific Git repo in `.idea/vcs.xml`. Otherwise, all seems fine.
